spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # 개발용 (운영에서는 validate 권장)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: never

jwt:
  secret: ${JWT_SECRET:dev-secret-change-me}
  ttlMillis: 900000

openai:
  api-url: https://api.openai.com/v1
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o-mini
  max-output-tokens: 500

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.security: DEBUG

server:
  port: 8080
